### ISSUE TITLE
联合声学模型和语言模型解码

### ISSUE THREAD

**Issue by Sundy1219** [audier/DeepSpeechRecognition#24]
您的项目非常棒，目前主流的算法，你都集成了．可关于解码这块，我还是有些问题，
你后面的解码是基于拼音解码正确的情况下，但是ctc decoder解码出来的音是有错误的，再接后面的语言模型，解出来肯定也是错误的，除非你语言模型有纠错功能，能将错误的音根据上下文解出正确的汉字，就像搜狗输入法一样，所以我认为还是要根据声学中音的概率以及语言模型中字的概率联合起来，去判断到底是哪一个汉字，我说出这个问题，是因为这个问题一直困扰着我，所以想问下您对此问题怎么看，有没有什么想法，期待您的回复，谢谢

**Comment by audier** [comment]
你好，我有一个思路，大概是用深度模型去做，我们训练的时候随机mask一些拼音或者随机修改一些输入拼音，但是label还是完整的中文，不知道这种做法是不是有效。我感觉用self attention应该有一定的效果的。
https://blog.csdn.net/chinatelecom08/article/details/85051817
因为谷歌的论文bert训练也用了类似的思路。他会 随机选一部分词语进行mask，这部分词语有可能被其他词代替，也有可能是mask，也有可能不做修改。不过我也没做实验，就是主管感受。
![image](https://user-images.githubusercontent.com/37586343/50223157-5a55ca80-03d5-11e9-837a-a9a2899f64fb.png)

**Comment by audier** [comment]
我还有个思路，就是后面不用ctc，在前面卷积后面加上encoder-decoder直接用文本进行训练。说不定有较好的 结果。

**Comment by Sundy1219** [comment]
我的想法是树拷贝动态解码，可还不知到咋弄．你的fsmn cell可以用吗？有测试过效果吗？我们现在测试fsmn确实比lstm好，不仅模型小，收敛速度都快很多，准确性也高很多

**Comment by whaozl** [comment]
@Sundy1219 fsmn 咋用啊 那个cell不知道怎么用 有提供使用说明吗
