### ISSUE TITLE
error: tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found

### ISSUE THREAD

**Issue by wujsy** [audier/DeepSpeechRecognition#25]
Hi, when i trained the cnn_ctc model, the error happened, do anyone have an idea?
my configure is as follows:

params = tf.contrib.training.HParams(
        # vocab
        data_type = 'train',
        data_path = './data/',
        thchs30 = True,
        aishell = True,
        prime = True,
        stcmd = True,
        batch_size = 16,
        data_length = None,
        shuffle = True)

the error happend when loss dropped to 28:
7492/17725 [===========>..................] - ETA: 43:19 - loss: 28.7227
 7493/17725 [===========>..................] - ETA: 43:19 - loss: 28.7226
 7494/17725 [===========>..................] - ETA: 43:19 - loss: 28.7219
 7495/17725 [===========>..................] - ETA: 43:19 - loss: 28.7221
 7496/17725 [===========>..................] - ETA: 43:18 - loss: 28.72152018-12-26 11:04:36.796989: W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.

 7497/17725 [===========>..................] - ETA: 43:18 - loss: inf
 7498/17725 [===========>..................] - ETA: 43:18 - loss: inf
 7499/17725 [===========>..................] - ETA: 43:17 - loss: inf
 7500/17725 [===========>..................] - ETA: 43:17 - loss: inf
 7501/17725 [===========>..................] - ETA: 43:17 - loss: inf
 7502/17725 [===========>..................] - ETA: 43:17 - loss: inf
 7503/17725 [===========>..................] - ETA: 43:16 - loss: inf

**Comment by audier** [comment]
It seems that there is some repeat char in the label.
I mean if the label is 'aaa', the label length is len('a_a_a')=5, while the input length is 4,  there will be a wrong.
but when the label is 'abc', there won't be wrong.
I'll add some code to check if  len(label)+len(blank)<=len(input). 
I guess that maybe a reson.

**Comment by audier** [comment]
Although I set the label length of 'aaa'  to be 3, but ctc will change it to 5.

**Comment by audier** [comment]
@wujsy Hi, I think I have fixed the problem.

**Comment by audier** [comment]
@wujsy please report it back if it worked, thank you.

**Comment by wujsy** [comment]
@audier Hi, it seems that loss problem has been resolved, but when i trained transformer LM, the following error is prompted:
load acoustic model...
2018-12-29 09:23:41.835588: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2018-12-29 09:23:41.835725: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-29 09:23:41.835753: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2018-12-29 09:23:41.835764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2018-12-29 09:23:41.836009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14178 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:d9:00.0, compute capability: 7.0)
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    input_batch, label_batch = next(batch)
  File "/data/workspace/ASR/DeepSpeechRecognition/utils.py", line 123, in get_lm_batch
    label_batch = np.array([self.han2id(line, self.han_vocab) + [0] * (max_len - len(line)) for line in label_batch])
  File "/data/workspace/ASR/DeepSpeechRecognition/utils.py", line 123, in <listcomp>
    label_batch = np.array([self.han2id(line, self.han_vocab) + [0] * (max_len - len(line)) for line in label_batch])
  File "/data/workspace/ASR/DeepSpeechRecognition/utils.py", line 130, in han2id
    return [vocab.index(han) for han in line]
  File "/data/workspace/ASR/DeepSpeechRecognition/utils.py", line 130, in <listcomp>
    return [vocab.index(han) for han in line]
ValueError: ' ' is not in list
I wonder whether it has anything to do with the changes in AM train part?

**Comment by audier** [comment]
could you update to the lastest code, and try it again?

**Comment by audier** [comment]
it seems i have sovled the problem, but i can't remmeber it clearly.

**Comment by audier** [comment]
@wujsy hi, thank you for share it, i have fixed the problem

**Comment by audier** [comment]
i add : line = ''.join(line.split(' ')) 
in:
`
	def han2id(self, line, vocab):
		line = ''.join(line.split(' '))
		return [vocab.index(han) for han in line]`

**Comment by audier** [comment]
it seems there's some mistakes in the feed_dict, the label_batch can't transform to a np array. 
it's a little complex, i want to fix  :ValueError: ' ' is not in list, and cause this error.
```	
def han2id(self, line, vocab):
		line = ''.join(line.split(' '))
		return [vocab.index(han) for han in line]
```
line = ''.join(line.split(' '))
this command reduce the label length in the batch, so the length of labels in the same batch maybe 
[15 15 14 15 15 15]
and if you np.array a list with that shape, there will raise an error.

**Comment by audier** [comment]
@wujsy thank you for your report.

**Comment by audier** [comment]
would you please try it again?

**Comment by wujsy** [comment]
@audier  Hi, I updated the utils.py file, but it reported the same error. if set 'data_length = 10', it's ok, but not ok if set 'data_length = None'.

**Comment by audier** [comment]
can you post the error info?

**Comment by audier** [comment]
could you update the ./data file and try again? 
i have test the model, it seems works well.

**Comment by audier** [comment]
![image](https://user-images.githubusercontent.com/37586343/50630454-ee9a6280-0f7b-11e9-8e7a-0ed6828fe03d.png)
