### ISSUE TITLE
训练好的模型不能使用

### ISSUE THREAD

**Issue by 15458wew** [audier/DeepSpeechRecognition#26]
你好，训练好的模型在只使用thchs数据集的情况下可以测试不能训练，训练会报错：dimension 1 in both shapes must be equal ，but are 1043 and 230，shape are 256，1043 and 256，230 for assign _62，with input shapes 256，1043。 256，230。

**Comment by 15458wew** [comment]
并且修改utils.py里的batch_size也会报错导致测试脚本也无法使用。

**Comment by audier** [comment]
你好，下载的模型配置是数据length为10，所以字典里只有230个，才会报错，测试代码其实是推断解码，batchsize设置为1才行。

**Comment by 15458wew** [comment]
你好，首先感谢您的回复，其次我想问一下，train.py文件包含声学模型的训练与语言模型的训练？我运行train.py只运行了语言模型的训练。所以想询问一下，如何指定训练声学模型或语言模型，只有注释代码这种方法吗？

**Comment by windowxiaoming** [comment]
将下载的模型删除，只使用thchs数据集，数据length为None，，其他参数不变，训练报错：
InvalidArgumentError (see above for traceback): logits and labels must be same size: logits_size=[35,2666] labels_size=[36,2666]，搞了好久，tensorflow调试也不是很方便，楼主帮忙看下啦。

**Comment by audier** [comment]
@15458wew 有epochs参数，设为0就是不训练了。

**Comment by audier** [comment]
@windowxiaoming 你好，很可能是拼音有35个，显示汉字有36个，我研究研究

**Comment by audier** [comment]
@windowxiaoming 你好，查到数据有问题，我改一下
`3628   35   36
3861   35   36
4320   35   36
4543   35   36
4773   35   36
4990   35   36
5227   35   36
5463   35   36
5693   35   36
5921   35   36
6149   35   36`

**Comment by audier** [comment]
@windowxiaoming 你好，查到数据有问题，我马上改一下。
`3628   35   36
3861   35   36
4320   35   36
4543   35   36
4773   35   36
4990   35   36
5227   35   36
5463   35   36
5693   35   36
5921   35   36
6149   35   36`

**Comment by audier** [comment]
@windowxiaoming 你好，问题已修改

**Comment by windowxiaoming** [comment]
@audier 感谢楼主效率回复，谢谢了。

**Comment by coranholmes** [comment]
> 
> 
> 你好，下载的模型配置是数据length为10，所以字典里只有230个，才会报错，测试代码其实是推断解码，batchsize设置为1才行。

我下载了最新的代码，看了下batchsize已经为1了，但是在运行test的时候还是出现了类似的问题，请问是怎么回事呢？我没有自己训练，就直接用的你提供的，其他都没修改。
```
loading acoustic model...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 86 and 230. Shapes are [256,86] and [256,230]. for 'Assign_62' (op: 'Assign') with input shapes: [256,86], [256,230].
```
