### ISSUE TITLE
训练loss问题

### ISSUE THREAD

**Issue by windowxiaoming** [audier/DeepSpeechRecognition#31]

**Comment by audier** [comment]
?

**Comment by windowwendykong** [comment]
楼主，我想问下，我在thchs数据上训练，batch_size=1,lr=0.0008,loss下降很慢如下图，您看这个正常吗？

`
this is the 1 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 383s 57ms/step - loss: 31.6748
this is the 2 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 354s 53ms/step - loss: 23.9430
this is the 3 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 355s 53ms/step - loss: 22.5111
this is the 4 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 355s 53ms/step - loss: 21.7297
this is the 5 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 355s 53ms/step - loss: 21.2012
this is the 6 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 355s 53ms/step - loss: 20.8054
this is the 7 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 355s 53ms/step - loss: 20.4914
this is the 8 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 355s 53ms/step - loss: 20.2319
this is the 9 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 356s 53ms/step - loss: 20.0117
this is the 10 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 355s 53ms/step - loss: 19.8211
this is the 11 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 355s 53ms/step - loss: 19.6533
this is the 12 th epochs trainning !!!
6694
Epoch 1/1
6694/6694 [==============================] - 355s 53ms/step - loss: 19.5036

**Comment by audier** [comment]
@windowwendykong 你好，可以适当修改网络结构或者学习率、dropout等。总的来说最后应该是可以收敛到比较低的loss的

**Comment by audier** [comment]
@windowxiaoming 你好，我还是不知道你想表达什么。。。
