### ISSUE TITLE
运行test/train报错

### ISSUE THREAD

**Issue by BBstu** [audier/DeepSpeechRecognition#32]
File "D:\Program Files\Anaconda3\envs\one\lib\site-packages\keras\engine\base_layer.py", line 128, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)

TypeError: ('Keyword argument not understood:', 'dropout')

请问一下大家，这个问题有没有遇到的，怎么解决，感谢

**Comment by audier** [comment]
你好，更新一下试试？

**Comment by BBstu** [comment]
谢谢回复，尝试过了，换了好几个版本的tf与keras，这个应该是环境的问题，硬是找不出来从哪下手。。。

**Comment by audier** [comment]
tensorflow 1.7+， keras 2.0+

**Comment by audier** [comment]
@BBstu 你好，最终解决了吗？

**Comment by BBstu** [comment]
不知道您用的是什么系统， 我在windows下面换了各种版本的tf跟keras还是没有解决，换了Ubuntu16.04的环境解决上面的TypeError，可以跑test了，刚入门，后面问题还没仔细研究，后面我还会持续关注的，遇到问题再来请教。谢谢了。
