### ISSUE TITLE
mutlti-gpu training problem

### ISSUE THREAD

**Issue by wujsy** [audier/DeepSpeechRecognition#33]
Hi, I tried to training model with multi-gpus, i  set gpu_nums = 2 in cnn_ctc.py, but found that there seems to be only one gpu working, what happened?
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  On   | 00000000:B1:00.0 Off |                    0 |
| N/A   61C    P0    59W / 250W |  15646MiB / 16130MiB |     77%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  On   | 00000000:D9:00.0 Off |                    0 |
| N/A   35C    P0    37W / 250W |    506MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by audier** [comment]
maybe you can use a larger batch size?

**Comment by audier** [comment]
![image](https://user-images.githubusercontent.com/37586343/50681551-de9b8500-1046-11e9-9b2f-63a0567fb5d3.png)

**Comment by wujsy** [comment]
Hi, what's your batch_size? There was OOM problem when i set batch_size=64(GPU memeory 16G), it seems i could only set batch_size < 64 , and only one gpu worked at full capacity.

**Comment by audier** [comment]
I can't figure out what's the differents between your mechine and mine.
I can set the batch size = 64 with 2 gpus.

**Comment by wujsy** [comment]
ok, thanks
