### ISSUE TITLE
十分感谢 关于self-attention 模型

### ISSUE THREAD

**Issue by Lebron-Kun** [audier/DeepSpeechRecognition#34]
您好，我也看了您用attention实现机器翻译的教程，发现机器翻译那个用的是En-De模型而这个拼音转汉字的却只用了En部分，想问一下，机器翻译和拼音转汉字的原理不是应该一样吗？为什么用得网络架构不一样，是哪个效果好吗还是什么情况？ 希望您能不吝赐教，十分感谢

**Comment by audier** [comment]
你好。这个参考bert,你可以了解一下

**Comment by audier** [comment]
https://blog.csdn.net/triplemeng/article/details/83053419

**Comment by Lebron-Kun** [comment]
好的，十分感谢  还有一个问题想请教您  这个模型训练的时候必须保证输入和输出一一对应吗 也就是说拼音和中文标签必须一一对应吗  因为我想直接把声学模型识别的拼音拿来训练但是由于声学模型效果一般有的可能会出现拼音识别不全的情况比如 训练的时候 拼音：da4 jia1 xia4 hao3 -->大 家 下 午 好 类似这样的数据可以训练吗  我试了一下这种数据不行 程序会报错 
![image](https://user-images.githubusercontent.com/40813230/50817933-77d8dd00-1360-11e9-91fc-ab1a0988de5e.png)
请问 这个模型处理的数据必须是一一对应的这种吗

**Comment by audier** [comment]
你好，这种不太行啊。可以研究个别的模型…

**Comment by Lebron-Kun** [comment]
就是说这个模型要求的数据格式就是一一对应的拼音和汉字？

**Comment by audier** [comment]
是的
