### ISSUE TITLE
您好，关于语音数据的标签

### ISSUE THREAD

**Issue by qianhangyong** [audier/DeepSpeechRecognition#35]
您好，想问下语音的标签数据您是哪里得到的，因为下载原始数据的时候我看到只有thchs-30是拼音和中文都有，其他几个数据集都没有标注数据。跑过您之前的代码，在ctc中会出现输入小于输出的问题，应该是前面做了卷积的缘故，改成了tensorflow设置ignore_longer_outputs_than_inputs=True就没问题了，keras好像没有这个参数，不知道您有没有遇到。不过识别自己的录音结果不太好。我跑过一个将拼音的音调去掉的模型，结合输入法的语言模型去做，因为我觉得这样后面拼音转中文的语料比较容易获取，而且可以获得网络词汇。

**Comment by Lebron-Kun** [comment]
> 您好，想问下语音的标签数据您是哪里得到的，因为下载原始数据的时候我看到只有thchs-30是拼音和中文都有，其他几个数据集都没有标注数据。跑过您之前的代码，在ctc中会出现输入小于输出的问题，应该是前面做了卷积的缘故，改成了tensorflow设置ignore_longer_outputs_than_inputs=True就没问题了，keras好像没有这个参数，不知道您有没有遇到。不过识别自己的录音结果不太好。我跑过一个将拼音的音调去掉的模型，结合输入法的语言模型去做，因为我觉得这样后面拼音转中文的语料比较容易获取，而且可以获得网络词汇。

python有很多脚本啊 可以把汉字转换成拼音 比如xpinyin 直接import 导入包就可以用了

**Comment by audier** [comment]
你好，你可以更新一下，最近我应该是修复了你说的问题

**Comment by audier** [comment]
我是用包自动生成的，不过遇到多音字有一定几率会不够准确
