### ISSUE TITLE
如何测试自己的语音数据

### ISSUE THREAD

**Issue by terranZY** [audier/DeepSpeechRecognition#36]
您好，请问，如何测试自己录制的语音数据？谢谢

**Comment by audier** [comment]
修改test.py #4.的内容

```python3


# 4. 进行测试-------------------------------------------
from utils import compute_fbank
your_file = 'e:/test.wav'
for i in range(1):
    # 载入训练好的模型，并进行识别
    x= compute_fbank(your_file)
    result = am.model.predict(x, steps=1)
    # 将数字结果转化为文本结果
    _, text = decode_ctc(result, train_data.am_vocab)
    text = ' '.join(text)
    print('文本结果：', text)
    with sess.as_default():
        text = text.strip('\n').split(' ')
        x = np.array([train_data.pny_vocab.index(pny) for pny in text])
        x = x.reshape(1, -1)
        preds = sess.run(lm.preds, {lm.x: x})
        got = ''.join(train_data.han_vocab[idx] for idx in preds[0])
        print('识别结果：', got)
sess.close()
```

这样修改应该没有问题，你试一下

**Comment by terranZY** [comment]
- 您好，有一个模型纬度的错误：

Traceback (most recent call last):
  File "test.py", line 58, in <module>
    result = am.model.predict(x, steps=1)
  File "/usr/local/python3.6.8/lib/python3.6/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/usr/local/python3.6.8/lib/python3.6/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/python3.6.8/lib/python3.6/site-packages/keras/engine/training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected the_inputs to have 4 dimensions, but got array with shape (978, 200)

**Comment by audier** [comment]
```py3
# 4. 进行测试-------------------------------------------
from utils import compute_fbank
your_file = 'e:/test.wav'
for i in range(1):
    # 载入训练好的模型，并进行识别
    x= compute_fbank(your_file)
    x= np.expand_dims(x, axis=0)
    result = am.model.predict(x, steps=1)
    # 将数字结果转化为文本结果
    _, text = decode_ctc(result, train_data.am_vocab)
    text = ' '.join(text)
    print('文本结果：', text)
    with sess.as_default():
        text = text.strip('\n').split(' ')
        x = np.array([train_data.pny_vocab.index(pny) for pny in text])
        x = x.reshape(1, -1)
        preds = sess.run(lm.preds, {lm.x: x})
        got = ''.join(train_data.han_vocab[idx] for idx in preds[0])
        print('识别结果：', got)
sess.close()
```

**Comment by terranZY** [comment]
您好，非常感谢指点，维度和您的例子做了对比，好像还需要增加一维 x= x[:,:,:, np.newaxis]
# 4. 进行测试-------------------------------------------
from utils import compute_fbank
your_file = 'e:/test.wav'
for i in range(1):
    # 载入训练好的模型，并进行识别
    x= compute_fbank(your_file)
    x= np.expand_dims(x, axis=0)
    x= x[:,:,:, np.newaxis]
    result = am.model.predict(x, steps=1)
    # 将数字结果转化为文本结果
    _, text = decode_ctc(result, train_data.am_vocab)
    text = ' '.join(text)
    print('文本结果：', text)
    with sess.as_default():
        text = text.strip('\n').split(' ')
        x = np.array([train_data.pny_vocab.index(pny) for pny in text])
        x = x.reshape(1, -1)
        preds = sess.run(lm.preds, {lm.x: x})
        got = ''.join(train_data.han_vocab[idx] for idx in preds[0])
        print('识别结果：', got)
sess.close()

**Comment by terranZY** [comment]
目前用训练集的语音，可以输出，但是，我用自己录制的语音发现会这样的错误：
Traceback (most recent call last):
  File "test.py", line 55, in <module>
    x= compute_fbank(your_file)
  File "/install/DeepSpeechRecognition/utils.py", line 212, in compute_fbank
    data_line = data_line * w # 加窗
ValueError: operands could not be broadcast together with shapes (400,2) (400,)
广播的时候shape的长度不一致，这应该需要怎么调整？谢谢

**Comment by audier** [comment]
你录单声道的音频，现在用的是双声道，可以取均值或者取一列
