### ISSUE TITLE
关于识别精度的问题

### ISSUE THREAD

**Issue by kidden** [audier/DeepSpeechRecognition#41]
你好！
我使用thchs30训练语料训练，使用dev测试，以下是程序部分输出：
loading acoustic model...
loading language model...
INFO:tensorflow:Restoring parameters from logs_lm\model_30
get source list...
load  thchs_dev.txt  data...
100%|██████████| 893/893 [00:00<?, ?it/s]
make am vocab...
100%|██████████| 10/10 [00:00<?, ?it/s]
make lm pinyin vocab...
100%|██████████| 10/10 [00:00<?, ?it/s]
make lm hanzi vocab...
100%|██████████| 10/10 [00:00<?, ?it/s]

 the  0 th example.
文本结果： er4 yi1 yan3 wo3 yu3 de si4 wo3 te4 de yan3 ping2 yi4 da4 you4 yan3 yuan4 de yi1 an1
原文结果： qi1 shi2 nian2 dai4 mo4 wo3 wai4 chu1 qiu2 xue2 mu3 qin1 ding1 ning2 wo3 chi1 fan4 yao4 xi4 jiao2 man4 yan4 xue2 xi2 yao4 shen1 zuan1 xi4 yan2
原文汉字： 七十年代末我外出求学母亲叮咛我吃饭要细嚼慢咽学习要深钻细研
识别结果： 二一演我与的四我特的演凭意大又演院的一安

 the  1 th example.
文本结果： lv4 yan3 xiao3 yan3 yan3 wo3 hai2 te4 chu1 si4
原文结果： chen2 yun2 tong2 zhi4 tong2 shi2 yao1 qiu2 gan4 bu4 ren4 zhen1 xue2 xi2 ye4 wu4 jing1 tong1 ye4 wu4 xiang4 yi1 qie4 ye4 wu4 nei4 hang2 ren2 xue2 xi2
原文汉字： 陈云同志同时要求干部认真学习业务精通业务向一切业务内行人学习
识别结果： 绿演小演演我还特出四

 the  2 th example.
文本结果： lv4 jin4 zhu4 chang3 se4 ta1 de she4 yan3 wo3 yi1 neng2 zi wo3 bao1 wang3 kuai4 shi1 bu2 xiao3 cheng1
原文结果： ling4 wai4 nv3 dan1 zhong1 guo2 dui4 hai2 you3 han2 jing1 na4 he2 yao2 yan4 ao4 yun4 pai2 ming2 di4 liu4 qi1 wei4 ye3 ke3 yu3 gao1 shou3 yi1 bo2
原文汉字： 另外女单中国队还有韩晶娜和尧燕奥运排名第六七位也可与高手一搏
识别结果： 绿进住场色她的舍眼我一能子我包往块诗不小称

 the  3 th example.
文本结果： jin4 cao3 xiao3 lao3 hai2 yu3 zi3 lao3 yi1 you4 lie4 de yan3 hei1 ji3 de te4 yi1 zhou4 bu2 xiao3 ran2
原文结果： de2 dao4 li3 gong1 pu3 e4 hao4 wen2 yi1 duo1 nu4 fen4 tian2 ying1 pai1 an4 er2 qi3 nu4 chi4 fan3 dong4 pai4 bei1 bi3 wu2 chi3
原文汉字： 得到李公朴噩耗闻一多怒愤填膺拍案而起怒斥反动派卑鄙无耻
识别结果： 进草小老还与子老一又趔的眼黑己的特一轴不小然

 the  4 th example.
文本结果： xiang1 gang3 yan3 zi yue4 de de yan3 zi zi3 le he4
原文结果： ju4 yin4 du4 guan1 yuan2 tou4 lu4 shuang1 fang1 tao3 lun4 le yin4 du4 kong4 zhi4 de ke4 shi2 mi3 er3 di4 qu1 mu4 qian2 de jin3 zhang1 ju2 shi4 wen4 ti2
原文汉字： 据印度官员透露双方讨论了印度控制的克什米尔地区目前的紧张局势问题
识别结果： 香港眼子月的的眼子子了贺

 the  5 th example.
文本结果： zou3 bing4 yan3 xiao3 yi1 wo3 yan3 te4 yi1 me yan3 lie4 jing1 zhou4 zi chu1
原文结果： yuan2 chan3 ou1 zhou1 de wu4 wang4 cao3 qi2 mao4 bu4 yang2 dan4 ming2 wen2 ou1 ya4 su2 cheng1 wu4 wang4 wo3 huo4 wu2 wang4 wo3
原文汉字： 原产欧洲的勿忘草其貌不扬但名闻欧亚俗称勿忘我或毋忘我
识别结果： 走病演小一我演特一么演趔惊轴子出

 the  6 th example.
文本结果： ke3 yan3 yi4 lao3 yan3 ping2 di4 yan3 di4 de neng2 shuai3 ran2
原文结果： liu2 xiao3 guang1 jiu3 duan4 yu3 wang2 lei3 liu4 duan4 zhi1 zhan4 zui4 wei4 ji1 lie4 ye3 shi4 zui4 wan3 jie2 shu4 de yi1 pan2 qi2 gong4 xia4 le er4 bai3 wu3 shi2 wu3 shou3
原文汉字： 刘小光九段与王磊六段之战最为激烈也是最晚结束的一盘棋共下了二百五十五手
识别结果： 可眼意老演凭地演地的能甩然

 the  7 th example.
文本结果： yi1 jin3 zhi1 zi yue4 yi4 ji3 kuai4 hui2 lao3 yuan3 ji3 yan3 zhu4 de qie you1 shuai3
原文结果： gen1 ju4 cun1 gui1 min2 yue1 ou1 da3 nve4 dai4 lao3 ren2 de wang2 mou3 er2 xi2 bei4 chu4 er4 bai3 yuan2 fa2 kuan3 bing4 jiao1 yi1 liao2 fei4 wu3 bai3 yuan2
原文汉字： 根据村规民约殴打虐待老人的王某儿媳被处二百元罚款并交医疗费五百元
识别结果： 一仅只子月意己块回老远己眼住的趄优甩

 the  8 th example.
文本结果： xiang1 yong4 cao3 mao4 huo4 wen2 de lao3 bu4 nong2 lao3 jia1 lao3 yan3 wo3 lao3 yi4 yan3 xiao3 yan3 jin4 yi1 tou2 yi1 qu4 zhu4 de cheng1
原文结果： dang1 chuan2 wang3 xia4 piao4 shi2 bai2 chun2 lu4 yang2 qi3 si4 ti2 zai4 an4 bian1 zhui1 sui2 hao3 xiang4 shi4 song4 xing2 yi4 zhi2 pao3 le shi2 ji3 li3 tai4 qin1 qie4 le
原文汉字： 当船往下漂时白唇鹿扬起四蹄在岸边追随好像是送行一直跑了十几里太亲切了
识别结果： 香用草帽或闻的老不农老家老演我老意演小演进一头一去住的称

 the  9 th example.
文本结果： zou3 qu4 wo3 zi3 yan3 yan3 huo2 xin1 dong4 you1
原文结果： kai1 luan2 kuang4 wu4 ju2 hou4 lv3 jia1 tuo2 kuang4 zhang1 wen2 you3 zhang1 wen2 fu4 liang3 xiong1 di4 tong2 chao1 chan3 tong2 li4 gong1 tong2 dang1 lao2 dong4 mo2 fan4
原文汉字： 开滦矿务局后吕家坨矿张文友张文富两兄弟同超产同立功同当劳动模范
识别结果： 走去我子演演活新动优
词错误率： 0.9771241830065359

WER出奇的高。
感觉深度学习框架识别精度不会这么低。请问，可能原因是什么？
期待你的答案。谢谢！

**Comment by kidden** [comment]
如果用train测试，识别正确率很高。但这是不可信的，因为训练数据不能作为测试数据使用。
感觉你的语音特征提取和一般的文献中不同，没有采用MFCC或FBANK等。是这个原因吗？

**Comment by audier** [comment]
你好，是重新用整个thchs30训练了吗？这个模型只能在训练集上看看，只训练了前十句话

**Comment by audier** [comment]
解码用的词典和训练的一致吗？

**Comment by theonly22** [comment]
@[windowwendykong](/windowwendykong)，改成date_length=none，4个数据集训练，
最后训练情况
28358/28359 [============================>.] - ETA: 0s - loss: 42.3508
你们训练到多少了？
