### ISSUE TITLE
语言模型训练

### ISSUE THREAD

**Issue by lilysongfei** [audier/DeepSpeechRecognition#42]
我用给的几个数据集进行语言模型的训练，发现训练的速度特别快，是我那里搞错了吗，然后loss降的特别慢，迭代几十次的结果完全不如这个工程给的语言模型的结果，这是为什么呢

**Comment by sunjunlishi** [comment]
请问各位大拿，我想训练一到九，九个数字的语言模型。声学模型不变可以吗？？

**Comment by audier** [comment]
你好，设置数据长度了吗？注意那个词典需要与训练data一致才行

**Comment by audier** [comment]
语言模型你可以参考tutorail单独跑一下试试？

**Comment by sunjunlishi** [comment]
还有我发现，我自己录的音识别几乎没有效果，16bit，16000HZ，单通道。
训练的语音数据测试还可以，就是你的Demo

**Comment by audier** [comment]
设置10只用前10条数据训练，设置为none用所有数据

**Comment by sunjunlishi** [comment]
@lilysongfei 你讲的很对，对于我那个问题。
