### ISSUE TITLE
求助：验证过程错误

### ISSUE THREAD

**Issue by theonly22** [audier/DeepSpeechRecognition#45]
28358/28359 [============================>.] - ETA: 0s - loss: 69.1157
28359/28359 [==============================] - 9126s 322ms/step - loss: 69.1155 - val_loss: 140.5556

Traceback (most recent call last):
  File "train.py", line 67, in <module>
    am.ctc_model.fit_generator(batch, steps_per_epoch=batch_num, epochs=10, callbacks=[checkpoint], workers=1, use_multiprocessing=False, validation_data=dev_batch, validation_steps=2)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.5/dist-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.5/dist-packages/keras/callbacks.py", line 429, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
KeyError: 'val_acc'

**Comment by theonly22** [comment]
训练代码是这样的，基本上没有改动：
import os
import tensorflow as tf
from utils import get_data, data_hparams
from keras.callbacks import ModelCheckpoint


# 0.准备训练所需数据------------------------------
data_args = data_hparams()
data_args.data_type = 'train'
data_args.data_path = '/home/wzg/all/data/speech_rec/'
data_args.thchs30 = True
data_args.aishell = True
data_args.prime = True
data_args.stcmd = True
# data_args.batch_size = 4
data_args.batch_size = 10
# data_args.data_length = 10
data_args.data_length = None
data_args.shuffle = True
train_data = get_data(data_args)

# 0.准备验证所需数据------------------------------
data_args = data_hparams()
data_args.data_type = 'dev'
data_args.data_path = '/home/wzg/all/data/speech_rec/'
data_args.thchs30 = True
data_args.aishell = True
data_args.prime = False
data_args.stcmd = False
# data_args.batch_size = 4
data_args.batch_size = 10
data_args.data_length = None
# data_args.data_length = 10
data_args.shuffle = True
dev_data = get_data(data_args)

# 1.声学模型训练-----------------------------------
from model_speech.cnn_ctc import Am, am_hparams
am_args = am_hparams()
am_args.vocab_size = len(train_data.am_vocab)
am_args.gpu_nums = 1
am_args.lr = 0.0008
am_args.is_training = True
am = Am(am_args)

if os.path.exists('logs_am/model.h5'):
    print('load acoustic model...')
    am.ctc_model.load_weights('logs_am/model.h5')

epochs = 10
batch_num = len(train_data.wav_lst) // train_data.batch_size

# checkpoint
ckpt = "model_{epoch:02d}-{val_acc:.2f}.hdf5"
checkpoint = ModelCheckpoint(os.path.join('./checkpoint', ckpt), monitor='val_acc', save_weights_only=False, verbose=1, save_best_only=True)

#
# for k in range(epochs):
#     print('this is the', k+1, 'th epochs trainning !!!')
#     batch = train_data.get_am_batch()
#     dev_batch = dev_data.get_am_batch()
#     am.ctc_model.fit_generator(batch, steps_per_epoch=batch_num, epochs=10, callbacks=[checkpoint], workers=1, use_multiprocessing=False, validation_data=dev_batch, validation_steps=200)

batch = train_data.get_am_batch()
dev_batch = dev_data.get_am_batch()

am.ctc_model.fit_generator(batch, steps_per_epoch=batch_num, epochs=10, callbacks=[checkpoint], workers=1, use_multiprocessing=False, validation_data=dev_batch, validation_steps=2)
# am.ctc_model.fit_generator(batch, steps_per_epoch=batch_num, epochs=10, callbacks=[], workers=1, use_multiprocessing=False, validation_data=dev_batch, validation_steps=200)
am.ctc_model.save('logs_am/model.h5')
# am.ctc_model.save_weights('logs_am/model.h5')

**Comment by wangyabo123** [comment]
您好，请问这个问题您解决了吗，我也遇到了同样的问题

**Comment by audier** [comment]
你好，检查一下
ckpt = "model_{epoch:02d}-{val_acc:.2f}.hdf5"
checkpoint = ModelCheckpoint(os.path.join('./checkpoint', ckpt), monitor='val_acc', save_weights_only=False, verbose=1, save_best_only=True)
可以试着删除掉monitor，或者查看一下文档monitor是否有这个val_acc名称。
这个是我merge的一个其他同学的提交，最近没实践验证，不好意思。
如果你解决了这个问题，请通知我。

**Comment by eeric** [comment]
@theonly22 
@wangyabo123 
@audier 

>>>modified following
ckpt = "model_{epoch:02d}-{val_loss:.2f}.hdf5"
checkpoint = ModelCheckpoint(os.path.join('./checkpoint', ckpt), monitor='val_loss', save_weights_only=False, verbose=1, save_best_only=True)

>>>output
Epoch 1/10
2/2 [==============================] - 198s 99s/step - loss: 377.5887 - val_loss: 391.7821

Epoch 00001: val_loss improved from inf to 391.78214, saving model to ./checkpoint/model_01-391.78.hdf5
Epoch 2/10
2/2 [==============================] - 155s 77s/step - loss: 302.0934 - val_loss: 198.3939

Epoch 00002: val_loss improved from 391.78214 to 198.39394, saving model to ./checkpoint/model_02-198.39.hdf5

>>>before this, folder created named checkpoint
ok, good luck!
