### ISSUE TITLE
建议楼主下次直接把声学模型和语言模型一起训练

### ISSUE THREAD

**Issue by zqs01** [audier/DeepSpeechRecognition#56]
transformer结构是端到端的，可以直接用transformer结构，声学模型和语言模型一起训练。

**Comment by Lebron-Kun** [comment]
> 
> 
> transformer结构是端到端的，可以直接用transformer结构，声学模型和语言模型一起训练。

您好  ，我现在也是在考虑能不能讲声学模型和语言模型放在一块训练？ 但是不知道怎么实施 ，您说的用transformer 怎么进行端到端的训练 声学模型和语言模型要怎么连接起来  ？还望赐教

**Comment by audier** [comment]
是的，transformer是可以直接输出汉字，而且不需要ctc就可以
