### ISSUE TITLE
transformer语言模型训练的loss问题

### ISSUE THREAD

**Issue by stephen-song** [audier/DeepSpeechRecognition#61]
博主您好，我使用了全部四种语料的文本数据进行语言模型的训练，几个超参设置是：batch=64，lr=0.0001,，经过19个epoch后，在测试集上能达到90%的acc，但是我发现训练过程中不管是训练集的acc和loss还是验证集的acc和loss，虽然整体趋势是在升高（acc）和降低（loss），但是这期间震荡的特别厉害（如图所示：<img src=http://www.kupan123.com/upload/1554727535x977010973.png />）不知道博主有没有遇到这种问题？

**Comment by stephen-song** [comment]
tensorboard 截图：http://www.kupan123.com/upload/1554727535x977010973.png

**Comment by melissazhou** [comment]
@stephen-song 请问你现在训练完成后，用自己录音的语音验证大概有多少ACC？
