### ISSUE TITLE
input_length 为什么要除以8 

### ISSUE THREAD

**Issue by shanengcn** [audier/DeepSpeechRecognition#93]
wav_lens = np.array([leng // 8 for leng in wav_lens])

**Comment by feelingstack** [comment]
cnn网络模型包含三个pooling层，最后模型的输出是  最长语音长度//8 乘以 字典的大小

**Comment by shanengcn** [comment]
> cnn网络模型包含三个pooling层，最后模型的输出是 最长语音长度//8 乘以 字典的大小

好的，明白啦，谢谢！
